# Translation of OpenERP Server.
# This file contains the translation of the following modules:
#	* pdi_connector
#
msgid ""
msgstr ""
"Project-Id-Version: OpenERP Server 7.0\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2014-03-12 15:37+0000\n"
"PO-Revision-Date: 2014-03-12 15:37+0000\n"
"Last-Translator: <>\n"
"Language-Team: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: \n"
"Plural-Forms: \n"

#. module: pdi_connector
#: help:pdi.instance.parameters,name:0
msgid "Name of the parameters, in upper case"
msgstr ""

#. module: pdi_connector
#: view:pdi.task:0
msgid "Information"
msgstr ""

#. module: pdi_connector
#: view:pdi.instance:0
msgid "PDI Instance"
msgstr ""

#. module: pdi_connector
#: model:ir.ui.menu,name:pdi_connector.menu_pdi_configuration_menu
msgid "Pentaho Data Integration"
msgstr ""

#. module: pdi_connector
#: selection:pdi.instance,version:0
msgid "v5.0"
msgstr ""

#. module: pdi_connector
#: field:pdi.instance,trans_ids:0
msgid "Transformations"
msgstr ""

#. module: pdi_connector
#: view:pdi.instance:0
#: field:pdi.instance,param_ids:0
#: view:pdi.instance.parameters:0
#: view:pdi.task:0
#: field:pdi.task,param_ids:0
#: view:pdi.transformation:0
#: field:pdi.transformation,param_ids:0
msgid "Parameters"
msgstr ""

#. module: pdi_connector
#: help:pdi.task,note:0
#: help:pdi.transformation,note:0
msgid "Explain the process for the user"
msgstr ""

#. module: pdi_connector
#: model:ir.model,name:pdi_connector.model_base_config_settings
msgid "base.config.settings"
msgstr ""

#. module: pdi_connector
#: code:addons/pdi_connector/pdi.py:362
#: code:addons/pdi_connector/pdi.py:628
#, python-format
msgid "(%s) Unknown error"
msgstr ""

#. module: pdi_connector
#: field:base.config.settings,module_pdi_connector:0
msgid "Active PDI module"
msgstr ""

#. module: pdi_connector
#: model:res.groups,name:pdi_connector.group_pdi_user
msgid "PDI / User"
msgstr ""

#. module: pdi_connector
#: field:pdi.instance,note:0
#: field:pdi.task,note:0
#: field:pdi.transformation,note:0
msgid "Note"
msgstr ""

#. module: pdi_connector
#: selection:pdi.task,level:0
#: selection:pdi.transformation,level:0
msgid "Debug"
msgstr ""

#. module: pdi_connector
#: view:pdi.instance:0
msgid "Real login in OpenERP"
msgstr ""

#. module: pdi_connector
#: code:addons/pdi_connector/pdi.py:622
#, python-format
msgid "(7) The task couldn't be loaded from XML or the Repository"
msgstr ""

#. module: pdi_connector
#: view:pdi.task:0
#: view:pdi.transformation:0
msgid "Debug information"
msgstr ""

#. module: pdi_connector
#: selection:pdi.task,level:0
#: selection:pdi.transformation,level:0
msgid "Basic"
msgstr ""

#. module: pdi_connector
#: help:pdi.instance,username:0
msgid "OpenERP User to connect tools with XMLRPC or NETRPC"
msgstr ""

#. module: pdi_connector
#: model:ir.actions.act_window,name:pdi_connector.act_open_pdi_instance_view
#: model:ir.ui.menu,name:pdi_connector.menu_pdi_instance
#: view:pdi.instance:0
#: field:pdi.instance.parameters,instance_id:0
#: view:pdi.task:0
#: field:pdi.task,instance_id:0
#: view:pdi.transformation:0
#: field:pdi.transformation,instance_id:0
msgid "Instance"
msgstr ""

#. module: pdi_connector
#: model:ir.actions.act_window,name:pdi_connector.act_open_pdi_transformation_view
#: model:ir.ui.menu,name:pdi_connector.menu_pdi_transformation
#: view:pdi.instance:0
#: field:pdi.trans.param,trans_id:0
#: view:pdi.transformation:0
msgid "Transformation"
msgstr ""

#. module: pdi_connector
#: model:ir.module.category,name:pdi_connector.module_category_etl_connector
msgid "ETL"
msgstr ""

#. module: pdi_connector
#: selection:pdi.instance,version:0
msgid "v3.2"
msgstr ""

#. module: pdi_connector
#: selection:pdi.task,level:0
#: selection:pdi.transformation,level:0
msgid "Rowlevel"
msgstr ""

#. module: pdi_connector
#: code:addons/pdi_connector/pdi.py:350
#: code:addons/pdi_connector/pdi.py:618
#, python-format
msgid "(1) Errors occurred during processing"
msgstr ""

#. module: pdi_connector
#: help:pdi.transformation,cron_id:0
msgid "If fill, this transformation is schedule"
msgstr ""

#. module: pdi_connector
#: code:addons/pdi_connector/pdi.py:620
#, python-format
msgid "(2) An unexpected error occurred during loading / running of the task"
msgstr ""

#. module: pdi_connector
#: field:pdi.task,log_cmd:0
#: field:pdi.transformation,log_cmd:0
msgid "Log Command"
msgstr ""

#. module: pdi_connector
#: code:addons/pdi_connector/pdi.py:354
#, python-format
msgid "(3) Unable to prepare and initialize this transformation"
msgstr ""

#. module: pdi_connector
#: model:ir.model,name:pdi_connector.model_pdi_instance_parameters
msgid "Parameters for this instance"
msgstr ""

#. module: pdi_connector
#: field:pdi.task,level:0
#: field:pdi.transformation,level:0
msgid "Level"
msgstr ""

#. module: pdi_connector
#: selection:pdi.instance,version:0
msgid "v4.2"
msgstr ""

#. module: pdi_connector
#: selection:pdi.instance,version:0
msgid "v4.0"
msgstr ""

#. module: pdi_connector
#: help:pdi.instance,repo_pass:0
msgid "Enter the password for this repository"
msgstr ""

#. module: pdi_connector
#: selection:pdi.task,state:0
#: selection:pdi.transformation,state:0
msgid "Running"
msgstr ""

#. module: pdi_connector
#: help:pdi.task,log_cmd:0
#: help:pdi.transformation,log_cmd:0
msgid "Log command file as info, usefull for debugging"
msgstr ""

#. module: pdi_connector
#: selection:pdi.instance,version:0
msgid "v4.4"
msgstr ""

#. module: pdi_connector
#: model:res.groups,name:pdi_connector.group_pdi_manager
msgid "PDI / Manager"
msgstr ""

#. module: pdi_connector
#: selection:pdi.task,level:0
#: selection:pdi.transformation,level:0
msgid "Nothing"
msgstr ""

#. module: pdi_connector
#: code:addons/pdi_connector/pdi.py:356
#, python-format
msgid "(7) The transformation couldn't be loaded from XML or the Repository"
msgstr ""

#. module: pdi_connector
#: field:pdi.instance,password:0
#: field:pdi.instance,repo_pass:0
msgid "Password"
msgstr ""

#. module: pdi_connector
#: help:pdi.instance.parameters,value:0
#: help:pdi.task.param,value:0
#: help:pdi.trans.param,value:0
msgid "Use [[Â ]] to eval, time, datetime, timedelta is available"
msgstr ""

#. module: pdi_connector
#: view:pdi.instance:0
#: view:pdi.task:0
#: view:pdi.transformation:0
msgid "Notes"
msgstr ""

#. module: pdi_connector
#: selection:pdi.instance,version:0
msgid "v4.3"
msgstr ""

#. module: pdi_connector
#: field:pdi.instance,repo_user:0
#: field:pdi.instance,username:0
msgid "Username"
msgstr ""

#. module: pdi_connector
#: field:pdi.task,state:0
#: field:pdi.transformation,state:0
msgid "Status"
msgstr ""

#. module: pdi_connector
#: code:addons/pdi_connector/pdi.py:406
#, python-format
msgid "\n"
"BE CAREFULL, record are incorrect for %s"
msgstr ""

#. module: pdi_connector
#: field:pdi.instance,name:0
#: field:pdi.instance,repo_name:0
#: field:pdi.instance.parameters,name:0
#: field:pdi.task,name:0
#: field:pdi.task.param,name:0
#: field:pdi.trans.param,name:0
#: field:pdi.transformation,name:0
msgid "Name"
msgstr ""

#. module: pdi_connector
#: model:ir.model,name:pdi_connector.model_pdi_task_param
msgid "Parameter to launch task"
msgstr ""

#. module: pdi_connector
#: view:pdi.instance:0
#: view:pdi.task:0
#: view:pdi.transformation:0
msgid "Launch"
msgstr ""

#. module: pdi_connector
#: help:pdi.instance,password:0
msgid "Password for the OpenERP User"
msgstr ""

#. module: pdi_connector
#: help:pdi.instance,repo_user:0
msgid "Enter the username for this repository"
msgstr ""

#. module: pdi_connector
#: code:addons/pdi_connector/pdi.py:258
#: code:addons/pdi_connector/pdi.py:531
#, python-format
msgid "pdi path does not exist"
msgstr ""

#. module: pdi_connector
#: field:pdi.instance.parameters,value:0
#: field:pdi.task.param,value:0
#: field:pdi.trans.param,value:0
msgid "Value"
msgstr ""

#. module: pdi_connector
#: model:res.groups,comment:pdi_connector.group_pdi_menu
msgid "Use to display the kettle as root menu\n"
"select another group (user or manager) to user the transformation or task"
msgstr ""

#. module: pdi_connector
#: code:addons/pdi_connector/pdi.py:360
#: code:addons/pdi_connector/pdi.py:626
#, python-format
msgid "(9) Command line usage printing"
msgstr ""

#. module: pdi_connector
#: model:ir.model,name:pdi_connector.model_pdi_transformation
msgid "Transformation of a PDI instance"
msgstr ""

#. module: pdi_connector
#: view:pdi.transformation:0
msgid "Install Cron"
msgstr ""

#. module: pdi_connector
#: selection:pdi.task,state:0
#: selection:pdi.transformation,state:0
msgid "Stopped"
msgstr ""

#. module: pdi_connector
#: code:addons/pdi_connector/pdi.py:258
#: code:addons/pdi_connector/pdi.py:531
#: selection:pdi.task,level:0
#: selection:pdi.transformation,level:0
#, python-format
msgid "Error"
msgstr ""

#. module: pdi_connector
#: field:pdi.task,directory:0
#: field:pdi.transformation,directory:0
msgid "Directory"
msgstr ""

#. module: pdi_connector
#: model:ir.model,name:pdi_connector.model_pdi_task
msgid "Task of a PDI instance"
msgstr ""

#. module: pdi_connector
#: code:addons/pdi_connector/pdi.py:352
#, python-format
msgid "(2) An unexpected error occurred during loading / running of the transformation"
msgstr ""

#. module: pdi_connector
#: selection:pdi.task,level:0
#: selection:pdi.transformation,level:0
msgid "Detailed"
msgstr ""

#. module: pdi_connector
#: view:pdi.transformation:0
msgid "Informations"
msgstr ""

#. module: pdi_connector
#: view:pdi.instance:0
#: field:pdi.instance,task_ids:0
msgid "Tasks"
msgstr ""

#. module: pdi_connector
#: model:ir.model,name:pdi_connector.model_pdi_instance
msgid "Instance of PDI server"
msgstr ""

#. module: pdi_connector
#: help:pdi.task,memory:0
#: help:pdi.transformation,memory:0
msgid "Custom memory to launch this treament, if 0 use standard"
msgstr ""

#. module: pdi_connector
#: view:pdi.task:0
#: view:pdi.transformation:0
msgid "Group By..."
msgstr ""

#. module: pdi_connector
#: selection:pdi.instance,version:0
msgid "v4.1"
msgstr ""

#. module: pdi_connector
#: model:ir.model,name:pdi_connector.model_pdi_trans_param
msgid "Parameter to launch transformation"
msgstr ""

#. module: pdi_connector
#: view:pdi.transformation:0
msgid "Uninstall Cron"
msgstr ""

#. module: pdi_connector
#: code:addons/pdi_connector/pdi.py:358
#: code:addons/pdi_connector/pdi.py:624
#, python-format
msgid "(8) Error loading steps or plugins (error in loading one of the plugins mostly)"
msgstr ""

#. module: pdi_connector
#: view:pdi.instance:0
#: view:pdi.task:0
#: view:pdi.transformation:0
msgid "General"
msgstr ""

#. module: pdi_connector
#: field:pdi.transformation,cron_id:0
msgid "Cron"
msgstr ""

#. module: pdi_connector
#: help:base.config.settings,module_pdi_connector:0
msgid "Install Pentaho Data Integration Connector for OpenERP"
msgstr ""

#. module: pdi_connector
#: field:pdi.instance,version:0
msgid "Version"
msgstr ""

#. module: pdi_connector
#: field:pdi.task,memory:0
#: field:pdi.transformation,memory:0
msgid "Memory"
msgstr ""

#. module: pdi_connector
#: view:pdi.instance:0
msgid "OpenERP for external integration"
msgstr ""

#. module: pdi_connector
#: view:pdi.instance:0
msgid "Repository information"
msgstr ""

#. module: pdi_connector
#: view:pdi.transformation:0
msgid "Scheduling"
msgstr ""

#. module: pdi_connector
#: model:ir.actions.act_window,name:pdi_connector.act_open_pdi_task_view
#: model:ir.ui.menu,name:pdi_connector.menu_pdi_task
#: view:pdi.instance:0
#: view:pdi.task:0
#: field:pdi.task.param,trans_id:0
msgid "Task"
msgstr ""

#. module: pdi_connector
#: view:base.config.settings:0
msgid "Penthao Data Inetgration"
msgstr ""

#. module: pdi_connector
#: model:res.groups,name:pdi_connector.group_pdi_menu
msgid "PDI / Menu"
msgstr ""

#. module: pdi_connector
#: help:pdi.instance,repo_name:0
msgid "Enter the name of the repository"
msgstr ""

